version: '2'
services:
    sociapp-app:
        image: sociapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sociapp-mysql:3306/sociapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=sociapp-elasticsearch:9300
        ports:
            - 8080:8080
    sociapp-mysql:
        extends:
            file: mysql.yml
            service: sociapp-mysql
    sociapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: sociapp-elasticsearch
